baseurl = "https://pothix.com"
languageCode = "en"
title = "PotHix"
disqusShortname = "pothixcom"
googleAnalytics = "UA-2852094-2"

[taxonomies]
tag = "tags"

[params]
description = "The personal website for Willian Molinari, also known as PotHix"
keywords = ["Programming", "Linux", "Desconstruindo a web", "Ruby", "Elixir", "Golang", "Guru-SP"]
author = "Willian Molinari a.k.a. PotHix"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "ruby", "elixir", "shell"]

[[params.social]]
url = "https://github.com/PotHix"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/pothix"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/PotHix"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/willianmolinari"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
