baseurl = "https://pothix.com"
languageCode = "en"
title = "PotHix"
# theme = "doctype"
theme = "hello-friend-ng"
disqusShortname = "pothixcom"
googleAnalytics = "UA-2852094-2"
paginate     = 10

[taxonomies]
  tag    = "tags"
  series = "series"

[permalinks]
post = "/:filename"


[params]
  description = "The personal website for Willian Molinari, also known as PotHix"
  keywords = ["Programming", "Linux", "Desconstruindo a web", "Ruby", "Elixir", "Golang", "Guru-SP", "Rust", "Productivity"]

  #############################################
  # hello-friend-ng params
  #############################################
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2, 2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  #############################################
  # doctype params
  #############################################
  author = "Willian Molinari a.k.a. PotHix"
  sharingicons = true

  [params.highlight]
  style = "github"
  languages = ["go", "dockerfile", "ruby", "elixir", "shell", "rust", "python"]

  [[params.social]]
  url = "https://github.com/PotHix"
  fa_icon = "fa-github"

  [[params.social]]
  url = "https://gitlab.com/pothix"
  fa_icon = "fa-gitlab"

  [[params.social]]
  url = "https://twitter.com/PotHix"
  fa_icon = "fa-twitter"

  [[params.social]]
  url = "https://linkedin.com/in/willianmolinari"
  fa_icon = "fa-linkedin-square"

  [[params.social]]
  url = "/index.xml"
  fa_icon = "fa-rss"

[languages]
  [languages.en]
    title = "PotHix"
    subtitle = "The personal website for Willian Molinari, also known as PotHix"
    keywords = "Programming, Linux, Desconstruindo a web, Ruby, Elixir, Golang, Guru-SP, Rust, Productivity"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    author = "Willian Molinari a.k.a. PotHix"
    sharingicons = true

    [languages.en.params.logo]
      logoText = ""
      logoHomeLink = "/"
      path = "/images/pothix-logo.svg"
      alt = "A drawing that represents myself, portrait, black and white"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "book"
    name       = "Book"
    url        = "/book"

  [[menu.main]]
    identifier = "code"
    name       = "Code"
    url        = "/code"

  [[menu.main]]
    identifier = "now"
    name       = "Now"
    url        = "/now"
